### ISSUE TITLE
Provide two exes instead.

### ISSUE THREAD

**Issue by iplayr5r** [Mauler125/r5apexsdk#47]
Hey.
I'm trying to run this awesome mod through Wine.
So the game launches but when I click ~ or F10 nothing appears it's because the scripts are not being injected.
This could be due to launcher using some call/function that Wine doesn't support.
I wonder if it would be possible to work around this?

**Comment by wannaplayr5r** [comment]
Would it be possible to compile two .exe instead that wouldn't require typing?
One for "1" dev and second for "2" release build.
launcher.exe didn't require this workaround because it automatically launched dev build.

**Comment by iplayr5r** [comment]
Could you release two exe instead? Similar to like it was before with launcher.exe
It's easier to run on Linux (Wine) with an exe that already launches in Dev or Release Build.
This is because when I run the current official exe echo 1 | returns "1" automatically and if I want to relaunch I have to restart the whole prefix but with two exe this isn't the case.

**Comment by PixieCore** [comment]
@iplayr5r This [commit](https://github.com/Mauler125/r5apexsdk/commit/d5b2e58dae31f9c0a8ed42973d7a32da8ab8ac69) addressed the issue by making everything cheat wise depend on ConVar/ConCommands so no more 2 dlls needed for loading, Debug will only be used for actually debugging the SDK and the launcher itself will be adjusted to reflect that in a later commit.
